# Site settings
title: Aditya Bobde
email: bobde005@umn.edu
description: Personal academic website
baseurl: ""
url: "https://adityabobde19.github.io"
max_width: 800px

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  news:
    output: true
    permalink: /news/:path/

# Navigation
header_pages:
  - about.md
  - teaching.md

# Required by plugins
third_party_libraries:
  download: false

filtered_bibtex_keywords: []

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - README.md
